name: report coverage data to code climate
on:
  push:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/run_test.yml
  coverage:
    needs:
      - test
    name: coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: code-coverage-report
      - uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: "coverage-report.lcov:lcov"
          debug: true
