name: release package
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  test:
    uses: ./.github/workflows/run_test.yml
  publish-npm:
    uses: ./.github/workflows/npm-publish.yml
    secrets: inherit
