# This workflow will publish a package to npm js if run UT workflow passed
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_run:
    workflows:
      - run UT
    types:
      - completed
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.ref_name }}
      - run: echo ${{ github.ref_type }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
