name: run UT
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    env:
      TEST_USER: testuser
      TEST_PW: passw0rd
      TEST_PORT: 10022
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: docker run --rm -p${TEST_PORT}:22 naoso5/test-sshd
      - run: npm run test
      - run: npm test
